### ISSUE TITLE
Run prettier after every JSON dump

### ISSUE THREAD

**Issue by vincerubinetti** [dashnowlab/STRchive#111]
Prettier formats JSON (among many other things) in the most standard, accepted way. It also seems to be more compact than the default Python/R JSON dumping, and imo it's more pretty.

Prettier has a CLI that you can call on specific files, from any language:
https://prettier.io/docs/en/cli.html

However, to install it, I think you need to have Node:
https://prettier.io/docs/en/install

I don't think it has any pre-compiled binaries that you could e.g. install via `apt-get`.

That's a pain, however if y'all have already been running the website locally, you will have already installed Bun and Node. Also, the common GitHub Action runners come [with Node pre-installed](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#language-and-runtime), so it should be easy to install there too.

So, I think in your Snakemake file, you'd have additional steps to install prettier (if not installed already), and then run it on the JSON files right at the very end. And we could just document that Node must be installed, in the same way that you should be documenting that Python (and probably other stuff like pip or R) needs to be installed to be able to run the Snakemake for development.

**Comment by hdashnow** [comment]
I added [jsbeautifier](https://github.com/beautifier/js-beautify?tab=readme-ov-file#python-1) to check-loci.py, which runs every time to check various json fields are correct.
What do you think of the current formatting? There are probably more settings I can mess with.

![Screenshot 2024-12-04 at 6 03 53 AM](https://github.com/user-attachments/assets/fba0c109-9aa7-4bda-942d-1c9eb6b9de67)

**Comment by hdashnow** [comment]
What do you think of this format? Close enough?

It's essentially this:
```json
[
{
  "some-field": ["a", "b", "c"]
},
{
  "some-field": ["a", "b", "c"]
}
]
```



![Screenshot 2024-12-09 at 1 13 21 PM](https://github.com/user-attachments/assets/10e00320-8942-433e-9159-c7e9634f6084)
![Screenshot 2024-12-09 at 1 13 36 PM](https://github.com/user-attachments/assets/2cb48e19-f120-4d98-ad2a-7b5c37fe380f)

**Comment by hdashnow** [comment]
If you think it's good enough, feel free to merge #119 and close this issue.
