### ISSUE TITLE
Suppress Additional Literature section when empty

### ISSUE THREAD

**Issue by hdashnow** [dashnowlab/STRchive#116]
As an example, opdm_abcd3 locus has nothing in the Additional Literature section because all citations are already in the References section above. This is likely to occur for any relatively new locus.

![Screenshot 2024-12-05 at 10 52 52 AM](https://github.com/user-attachments/assets/fdc69ed3-c6da-4fb6-af4a-92c9c5f556ae)

**Comment by hdashnow** [comment]
I don't think the "All results" link is needed in this case, as it's just pointing to citations that are already listed above and could end up confusing the user.
Is that okay with you, @laurelhiatt ?

**Comment by laurelhiatt** [comment]
I think if additional literature is empty, we can remove the "additional literature related to this locus" sentence, but I want to keep the *.txt pointing for sure since those files have abstract and other information too bulky for each locus bibliography

**Comment by hdashnow** [comment]
Sorry @vincerubinetti, it turned out @laurelhiatt disagreed with me. We have had a side-bar and come to an agreement:

The link to the .txt file should say something like this:
All pubmed results returned by searching for this gene, tandem repeats, and disease (in medline format)

If the link is the only thing in this section, I think the bit that says "Additional literature related to this locus" should be removed. 
If there's no txt file at all for the gene, then this section is not needed at all.

**Comment by laurelhiatt** [comment]
Indubitably

**Comment by vincerubinetti** [comment]
Closed with https://github.com/dashnowlab/STRchive/commit/46f5935adc7e5293ef9d3cbd95f8901e545a12c0 and subsequent tweak commits. I was going to make a PR but accidentally pushed to main.

Note that that text you provided is a mouthful, so I made the actual link text shorter, and put the full sentence in parens next to it.

**Comment by vincerubinetti** [comment]
Please do verify that those commits look okay to you.

**Comment by hdashnow** [comment]
Looks great to me!
