### ISSUE TITLE
Citation on the CANVAS locus page not being converted to a number

### ISSUE THREAD

**Issue by hdashnow** [dashnowlab/STRchive#129]
[pmid:38627134] isn't being converted to a numerical citation.

It looks like it's correctly formatted in STRchive-loci.json in both the details and the references, but it's not present in STRchive-citations.json.

Ideally, the fallback should still produce a numerical citation. And then I also need to figure out why it's missing from STRchive-citations.json.

<img width="1042" alt="Screenshot 2024-12-18 at 5 22 38 AM" src="https://github.com/user-attachments/assets/a2a09bb1-2b5f-44f3-8a71-1424f0569be8" />
<img width="537" alt="Screenshot 2024-12-18 at 5 22 23 AM" src="https://github.com/user-attachments/assets/5ad0dc7c-fd4d-4b9a-8d8c-1d38c15bc66e" />

**Comment by laurelhiatt** [comment]
I think it's because it doesn't have an @, it needs the @, alas

**Comment by laurelhiatt** [comment]
created a pull request

**Comment by hdashnow** [comment]
Duh! Thank you. I missed that.
