### ISSUE TITLE
mm39 pathogenic_repeats.bed

### ISSUE THREAD

**Issue by uso2015** [dashnowlab/STRchive#18]
Hi，

        I use mm39 genome to analyse by TRGT which need pathogenic_repeats.bed file， how to get the file ? 

thanks

**Comment by hdashnow** [comment]
Hi, STRchive only contains human loci. Are you looking to genotype orthologous regions to these loci in mouse? If so, you'd need to establish those regions. If you're genotyping a humanized mouse model, again you'd need to establish custom regions.
If you're looking to genotype native tandem repeats in the mouse genome, you could use the USCS TRF annotation of the mouse genome as a starting point to generate a TRGT bed file.
https://genome.ucsc.edu/cgi-bin/hgTables?db=mm39&hgta_group=varRep&hgta_track=simpleRepeat&hgta_table=simpleRepeat&hgta_doSchema=describe+table+schema
