### ISSUE TITLE
ATXN7 Prevalence add leading 0?

### ISSUE THREAD

**Issue by hdashnow** [dashnowlab/STRchive#34]
https://github.com/dashnowlab/STRchive/blob/6ccbe2de8a3f94a5959bd2530057024f06ed77c5/data/STRchive-database.json#L757

A leading 0 might make this easier to read. Is this number correct @laurelhiatt ?

**Comment by laurelhiatt** [comment]
Yes, that makes sense Best,LaurelOn Sep 23, 2024, at 11:33 PM, Harriet Dashnow ***@***.***> wrote:﻿
https://github.com/dashnowlab/STRchive/blob/6ccbe2de8a3f94a5959bd2530057024f06ed77c5/data/STRchive-database.json#L757
A leading 0 might make this easier to read. Is this number correct @laurelhiatt ?
