### ISSUE TITLE
Propose removing/changing fields

### ISSUE THREAD

**Issue by hdashnow** [dashnowlab/STRchive#44]
I propose we do the following:

**Delete:**
"width" - this is the width of the locus in the ref genome. Not needed as it can be easily computed from start/end.
"normal" - this is the text version of the normal range. Would still keep normal_min, normal_max
"pathogenic" - text version of pathogenic range
"intermediate" - text version of intermediate range
Could potentially roll any complexity currently in the above into one of the notes/details fields.

"notes_t2t" - contains number of copies in t2t ref. Not sure if we need this. e.g. "(GCC)14.7"

**Rename** and/or combine to make it clearer what their uses are:
"notes":null,
"details":null,
"disease_description"
For example, do we need notes and details? Could notes be removed entirely and any needed content moved to details?

"type":"Intronic"
"location_in_gene":"Intron 32"

Thoughts? Any other fields that should be cleaned up?

**Comment by vincerubinetti** [comment]
Consistent casing and other formatting would be good too. Some fields are capitalized, some fields are abbreviated, some are CamelCase, some are snake_case. Probably should all be lower_snake_case.

**Comment by avvaruakshay** [comment]
Just adding possible things we could explore for JSON structure

- A multi level JSON structure to organise info regarding one condition under one key
- Boolean values indicating types of pathogenecity (motif heterogeneity, expansion, contraction)

**Comment by hdashnow** [comment]
**Updated summary of proposed changes:**

**Delete:**
"width" - this is the width of the locus in the ref genome. Not needed as it can be easily computed from start/end.
"normal" - this is the text version of the normal range. Would still keep normal_min, normal_max
"pathogenic" - text version of pathogenic range
"intermediate" - text version of intermediate range
"notes_t2t" - contains number of copies in t2t ref. Not sure if we need this. e.g. "(GCC)14.7"
"notes" - move content to details
"type":"Intronic" - move content to location_in_gene

**Rename**
Most are changes to snake_case, but some are for clarity

normal_min -> benign_min
normal_max -> benign_max
repeatunitlen -> motif_len

Mechanism -> mechanism 
Mechanism_detail -> mechanism_detail
Mechanism_source -> mechanism_source  # or could include citations in mechanism detail and remove this field?
OMIM -> omim
Prevalence -> prevalence
Prevalence_details -> prevalence_details
STRipy_gene -> stripy
gnomAD_gene -> gnomad
GeneReviews -> genereviews
Mondo -> mondo
Year -> year
MedGen -> medgen
Orphanet -> orphanet
GARD -> gard
WebSTR_hg38 -> webstr_hg38
WebSTR_hg19 -> webstr_hg19
TRgnomAD -> tr_gnomad

**Possible new fields**
strength_evidence - basically to flag conflicting evidence, new loci with minimal evidence etc.
observations - number of families reported

**Still to be determined:**
intermediate_min -> premutation_min ?? need multiple categories here?

**Comment by hdashnow** [comment]
Update after discussion today, so additional proposals:

**New fields**
observations - number of independent families reported in the literature with a pathogenic variant at that locus
locus_tags - categorical tags useful for filtering or adding icons, for example: "conflicting evidence", "expansion", "contraction"
disease_tags - categories of disease to allow grouping of similar diseases, for example, "spinocerebellar ataxia", "neurodegenerative"


Also note: 
- I will merge pending json changes before making this update. 
- I will have to keep this new json format in branch and not merge it into main until the new website goes live because this will break the old website. 
- I will also have to do a major version of the data when this eventually makes its way into main.

**Comment by hdashnow** [comment]
This is almost ready. @vincerubinetti what format do you think for the "tag" type json fields to be used for filtering and linking.
Could be `"disease_tags":['ataxia', 'epilepsy']`.
Or just keep it as delimited strings like other fields e.g. `"disease_tags":"ataxia; epilepsy"`.
Speaking of which, I should make sure all the delimiters are the same. Currently a mix of `;` and `,`. Any preference?
