### ISSUE TITLE
Table search: htt returns all

### ISSUE THREAD

**Issue by hdashnow** [dashnowlab/STRchive#62]
Searching "htt" in the loci table doesn't filter it. I'm guessing under the hood it's returning any locus with a URL? For example "HTTP" also returns all loci.
This is a problem because the most famous tandem repeat gene is Huntington's, which is abbreviated "HTT"
Can the table search only search the visible text rather than links as well?

<img width="1166" alt="Screenshot 2024-11-14 at 1 49 48 PM" src="https://github.com/user-attachments/assets/6175b4e3-0756-40cd-a39b-e605ce684857">

**Comment by vincerubinetti** [comment]
Here's the code for that:
https://github.com/dashnowlab/STRchive/blob/app/site/src/pages/loci/_Table.jsx#L109

I can make it do only the visible fields, though I thought maybe being able to search the details could be useful.

**Comment by vincerubinetti** [comment]
Changed in https://github.com/dashnowlab/STRchive/commit/b10f6a1e8cd9b892c08537dc292fdbd4b3d39739

**Comment by hdashnow** [comment]
Ability to search details would be nice. Another option would be to exclude URLs?
