### ISSUE TITLE
gnomAD plot suggestions

### ISSUE THREAD

**Issue by hdashnow** [dashnowlab/STRchive#76]
1. Suggest hover over for the x axis: Pathogenic Genotype (%): % of individuals predicted to be affected based on their genotype
1. gnomAD plot needs a legend for the red diamonds and blue bars. I'm assuming this is the estimate and 90% CI. Alternatively, using more standard error bar plotting style would make a legend unnecessary. 
1. We should either remove plots for the loci we deem to be genotyped unreliable in gnomAD or add some kind of warning so people don’t take them literally. For example, HOXA13 loci aren't actually that common, they're just hard to genotype.

**Comment by vincerubinetti** [comment]
Completed in recent PR (can't remember which).

**Comment by vincerubinetti** [comment]
Now actually closed by #85
