### ISSUE TITLE
intermediate allele plots on specific locus pages

### ISSUE THREAD

**Issue by laurelhiatt** [dashnowlab/STRchive#83]
@vincerubinetti I think these would be good to have before the website goes live

**Comment by vincerubinetti** [comment]
This is already there though?
https://strchive.netlify.app/loci/fraxe_aff2/#alleles

**Comment by laurelhiatt** [comment]
:O forgive me I have goofed

**Comment by vincerubinetti** [comment]
I snuck it into #79 in https://github.com/dashnowlab/STRchive/pull/79/commits/1cc706968da14802669b38c7e32463d0b1b53d4f
