### ISSUE TITLE
TR-gnomAD renamed to TR-atlas with URL change

### ISSUE THREAD

**Issue by hdashnow** [dashnowlab/STRchive#87]
<img width="1441" alt="Screenshot 2024-11-27 at 7 11 09 AM" src="https://github.com/user-attachments/assets/ae193f1c-0274-4b65-9515-429be87419fe">

Both websites are currently live, but unsure if they will transition to TR-atlas only in the future:
- https://wlcb.oit.uci.edu/TRgnomAD/ - old website
- https://wlcb.oit.uci.edu/TRatlas/ - new website

We will need to:
- [x] update the json field name from `tr_gnomad` -> `tr_atlas`
- [x] update the URL format for links out to that resource

**Comment by laurelhiatt** [comment]
done and done. should be fixed with the next website update.
