### ISSUE TITLE
Reviewer request: download table on loci page

### ISSUE THREAD

**Issue by laurelhiatt** [dashnowlab/STRchive#88]
@vincerubinetti One of the reviewer requests was to download the subset table on the loci page directly on that page. Could we make that happen?

**Comment by vincerubinetti** [comment]
Added a basic version of this in https://github.com/dashnowlab/STRchive/commit/7fb31ac789b60909ad4fa44ee0439d92b1f63c91

It downloads in JSON format. To do CSV, I'd have to install a library just for that, and also collapse the array entries e.g. tags down to semi-colon-separated strings or something. I'd probably only do this if a reviewer is really adamant it be added.
