### ISSUE TITLE
upload "blueprint" to resources page of STRchive

### ISSUE THREAD

**Issue by laurelhiatt** [dashnowlab/STRchive#90]
yo @vincerubinetti, we have a "blueprint" (color-coded google sheet) associated with the manuscript that I would love to get on the resources page, whether as a link to a google doc containing it, as a file that can be opened, idk what our options are, but I'm sure you do! 2.25 page spreadsheet by the way

**Comment by vincerubinetti** [comment]
We could put this as HTML tables in the website, but after seeing the document, I feel like we should out-link to this. It's a lot of info info to show on a website page (it's more of a paper figure), and I feel like we should just have it in one place to reduce duplication. Once the manuscript is published or whenever this table lands in its permanent public place, we can quickly add a (prominent?) link to it on the website.

**Comment by vincerubinetti** [comment]
Is the final document (where it's going to be permanently) going to be a Google Doc? If so, we can just link to that particular table within the document, no need to duplicate the info in another doc.

https://edu.gcfglobal.org/en/googledocuments/linking-within-a-document/1/

**Comment by laurelhiatt** [comment]
@vincerubinetti could you set it up perchance pretty please?

**Comment by laurelhiatt** [comment]
actually I may have set... something up

**Comment by laurelhiatt** [comment]
I think we're about there

**Comment by vincerubinetti** [comment]
Links:
https://docs.google.com/document/d/1MdWLtU9VVHnNvY5YwI3x_jomDTlXTRCbiejgNSZfYcg/edit?tab=t.0
https://docs.google.com/spreadsheets/d/14KX3dehixmnKv0EtG6eDRpD35nBPY-ooYUwRXqnaTqQ/edit?gid=0#gid=0

I've fixed up what you pushed to the branch. I'd recommend just linking to the google doc directly, as I could see this table forgotten to be updated on the website. I'd also recommend changing the line below the heading to something like "A detailed guide to evaluating and interpreting alleles, phenotypes, and loci for the construction of STR resources."
